apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-test
  namespace: kafka-test
spec:
  ttlSecondsAfterFinished: 86400  # Keep job for 1 day after completion
  template:
    spec:
      containers:
      - name: kafka-test
        image: ghcr.io/ksilin/kafka-autotest:0.0.1
        imagePullPolicy: Always
        args:
        - "-c"
        - "/config/client.properties"
        - "-t"
        - "test-topic-$(POD_UID)"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: truststore-volume
          mountPath: /certs
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
      volumes:
      - name: config-volume
        configMap:
          name: kafka-client-properties
      restartPolicy: Never
  backoffLimit: 2
