apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-client-properties
  namespace: kafka-test
data:
  client.properties: |
    bootstrap.servers=kafka-0.kafka.confluent.svc.cluster.local:9071
    security.protocol=SASL_SSL
    sasl.mechanism=PLAIN
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="kafka-secret";
    ssl.endpoint.identification.algorithm=
    ssl.truststore.type=PKCS12
    ssl.truststore.location=/certs/truststore.p12
    ssl.truststore.password=mystorepassword
    group.id=kafka-validation-group
    client.id=kafka-validation-client
    acks=-1
